### PR TITLE
Added Navbar v1

### PR DESCRIPTION
**Pull request by geekysilento**
image

Issues: Not very Responsive

### CODE REVIEW

**Comment by geekysilento** [comment]
made navbar responsive for all screen sizes
image
image

**Comment by heydoyouknowme0** [comment]
nav length, keeps on going for high-res displays. (Max limit might make it saner?)
Shouldn't "add listing" text be hidden before the logo.
Switch to a search Icon on smaller displays?

**Comment by aryansri-19** [comment]
Hidden before the logo means?

**Comment by heydoyouknowme0** [comment]
As the width decreases the logo gets hidden first, then then the text in "new post" button.

**Review by aryansri-19 — APPROVED** [review]
Seems right

**Pull request merged**
