### PR TITLE
Carousel add

### PR DESCRIPTION
**Pull request by aryansri-19**
image

https://github.com/DevsThatMatter/nksm/assets/75990590/42d796a1-78de-4fc5-8806-2c4c3dd995ef

### CODE REVIEW

**Comment by geekysilento** [comment]
image

fix title text cutting off, decrease font size of description, Title font should be larger than description

**Comment by heydoyouknowme0** [comment]
Baba height consistent karke skeleton add kardo

**Comment by aryansri-19** [comment]
Screenshot 2024-01-27 173636
Screenshot 2024-01-27 173643
Screenshot 2024-01-27 173656
Screenshot 2024-01-27 173710
Screenshot 2024-01-27 173718

in different resolutions

**Review by geekysilento — APPROVED** [review]
image

**Pull request merged**
