### PR TITLE
Categories cards done

### PR DESCRIPTION
**Pull request by aryansri-19**
Added category cards and respective images
image
image

### CODE REVIEW

**Comment by geekysilento** [comment]
categories text color is darker for some categories, lighter for some. Other than that looks good

**Comment by aryansri-19** [comment]
hmm, will change that

**Comment by geekysilento** [comment]
some text looks stretched out, check aspect ratio eg: stationary

**Comment by aryansri-19** [comment]
image
image

now?

**Review by geekysilento — APPROVED** [review]
looks good

**Pull request merged**
