### PR TITLE
Feature/add listing

### PR DESCRIPTION
**Pull request by som-04**
Form UI and Validation done

### CODE REVIEW

**Comment by aryansri-19** [comment]
because of toast, the preview component has become client-sided... know a way to fix?

**Comment by heydoyouknowme0** [comment]
toasts are boring, just redirect to products page or an error page is enough imo

**Comment by aryansri-19** [comment]
but a whole page for a confirmation message? status messages should be minimal in display

**Comment by heydoyouknowme0** [comment]
If there's an error on the server side it's a big thing

**Comment by aryansri-19** [comment]
> If there's an error on the server side it's a big thing, it should not error out in the first place normally. Confirmation will just route to the product page.

but what if something happened on the server side like mongodb issue or r2 issue, no message to the user that server error occurred?

**Comment by heydoyouknowme0** [comment]
> > If there's an error on the server side it's a big thing, it should not error out in the first place normally. Confirmation will just route to the product page.
> 
> but what if something happened on the server side like mongodb issue or r2 issue, no message to the user that server error occurred?

that is why theres an error page, mongo error should not happen when a site it working normally

**Comment by aryansri-19** [comment]
> > > If there's an error on the server side it's a big thing, it should not error out in the first place normally. Confirmation will just route to the product page.
> > 
> > 
> > but what if something happened on the server side like mongodb issue or r2 issue, no message to the user that server error occurred?
> 
> that is why theres an error page, mongo error should not happen when a site it working normally

i could be but its okay if there's a universal error page

**Comment by heydoyouknowme0** [comment]
cannot change branch closing

**Pull request closed without merging**
